#!/usr/bin/env python3
r"""Generate runtime/engram_norm.inc: the per-code-point form of the normaliser
`inference/engram.py` builds its compressed token map with (Track R2,
docs/p4_kv_ux.md §5).

`build_compressed_token_map` runs NFKC, NFD, StripAccents, Lowercase and three
whitespace rules over every decoded token. The first four are a function of one
code point at a time: NFD after NFKC is NFKD (canonically equivalent), NFKD is a
per-code-point decomposition plus a reordering of marks with a nonzero combining
class -- all of which StripAccents deletes -- and Lowercase maps each char on its
own. So `f(c) = pipeline(chr(c))` over every scalar value, concatenated, IS the
pipeline over a string. This script takes f from HF tokenizers' own normaliser
(the one engram.py runs) and checks that claim over all 129,280 tokens of the
checkpoint's tokenizer before writing anything.

    .venv/Scripts/python.exe tools/gen_engram_norm.py [--model DIR]
"""
import argparse
import os
import sys

from tokenizers import Regex, Tokenizer, normalizers

SBASE, LBASE, VBASE, TBASE, TCOUNT, NCOUNT = 0xAC00, 0x1100, 0x1161, 0x11A7, 28, 588


def hangul(cp):
    s = cp - SBASE
    out = [LBASE + s // NCOUNT, VBASE + (s % NCOUNT) // TCOUNT]
    if s % TCOUNT:
        out.append(TBASE + s % TCOUNT)
    return "".join(map(chr, out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=os.environ.get("DEEPMOE_MODEL_DIR", r"D:\models\DeepSeek-V4.1-Flash"))
    args = ap.parse_args()
    core = normalizers.Sequence([normalizers.NFKC(), normalizers.NFD(), normalizers.StripAccents(),
                                 normalizers.Lowercase()])
    table = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        o = core.normalize_str(chr(cp))
        if o != chr(cp):
            table[cp] = o

    # Hangul syllables are algorithmic; check, then leave them out of the table.
    for cp in range(SBASE, SBASE + 11172):
        assert table.get(cp) == hangul(cp), hex(cp)
        del table[cp]

    deleted = sorted(cp for cp, o in table.items() if o == "")
    singles = sorted(cp for cp, o in table.items() if len(o) == 1)
    multis = sorted(cp for cp, o in table.items() if len(o) > 1)

    def ranges(cps):
        out = []
        for c in cps:
            if out and out[-1][1] + 1 == c:
                out[-1][1] = c
            else:
                out.append([c, c])
        return out

    # single-char outputs as (lo, hi, stride, delta) runs
    runs = []
    for c in singles:
        d = ord(table[c]) - c
        if runs:
            lo, hi, st, dd = runs[-1]
            if dd == d and ((lo == hi and c - hi in (1, 2)) or (lo != hi and c - hi == st)):
                runs[-1] = [lo, c, c - lo if lo == hi else st, d]
                continue
        runs.append([c, c, 1, d])

    # verify the concatenation claim against the reference pipeline
    full = normalizers.Sequence(
        [normalizers.NFKC(), normalizers.NFD(), normalizers.StripAccents(), normalizers.Lowercase(),
         normalizers.Replace(Regex(r"[ \t\r\n]+"), " "), normalizers.Replace(Regex(r"^ $"), "\ue000"),
         normalizers.Strip(), normalizers.Replace("\ue000", " ")])
    tok = Tokenizer.from_file(os.path.join(args.model, "tokenizer.json"))
    hang = {cp: hangul(cp) for cp in range(SBASE, SBASE + 11172)}
    for i in range(tok.get_vocab_size()):
        text = tok.decode([i], skip_special_tokens=False)
        if "\ufffd" in text:
            continue
        ref = normalizers.Sequence([normalizers.NFKC(), normalizers.NFD(), normalizers.StripAccents(),
                                    normalizers.Lowercase()]).normalize_str(text)
        mine = "".join(table.get(ord(ch), hang.get(ord(ch), ch)) for ch in text)
        assert mine == ref, (i, text, ref, mine)
        full.normalize_str(text)

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo, "runtime", "engram_norm.inc")
    lines = ["// Generated by tools/gen_engram_norm.py from HF tokenizers' own normaliser",
             "// (NFKC, NFD, StripAccents, Lowercase, one code point at a time). Do not edit.",
             f"// {len(deleted)} deleted code points, {len(singles)} single-char maps in {len(runs)} runs,",
             f"// {len(multis)} multi-char maps; Hangul syllables are decomposed algorithmically.", ""]

    def emit(name, typ, rows, per):
        lines.append(f"static const {typ} {name}[][{per}] = {{")
        row = []
        for r in rows:
            row.append("{" + ",".join(f"0x{x:X}" if isinstance(x, int) and x >= 0 else str(x) for x in r) + "}")
            if len(row) == 6:
                lines.append("    " + ",".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ",".join(row) + ",")
        lines.append("};")
        lines.append("")

    emit("kNormDelete", "uint32_t", ranges(deleted), 2)
    emit("kNormRuns", "int32_t", runs, 4)
    flat, idx = [], []
    for c in multis:
        o = table[c]
        idx.append([c, len(flat), len(o)])
        flat.extend(ord(x) for x in o)
    emit("kNormMulti", "uint32_t", idx, 3)
    lines.append("static const uint32_t kNormMultiOut[] = {")
    for i in range(0, len(flat), 12):
        lines.append("    " + ",".join(f"0x{x:X}" for x in flat[i:i + 12]) + ",")
    lines.append("};")
    lines.append("")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{out_path}: {len(deleted)} deleted, {len(runs)} runs, {len(multis)} multi", file=sys.stderr)


if __name__ == "__main__":
    main()
