#!/usr/bin/env python3
r"""Generate text/unicode_tables.inc: the character classes the DeepSeek-V4.1
pre-tokenizer regexes use (\p{N} \p{L} \p{M} \p{P} \p{S} \s), taken from the
regex engine HF `tokenizers` itself runs, not from Python's unicodedata -- so the
C++ tokenizer agrees with the reference on every code point by construction.

For each class, one Split(Regex(cls), "removed") over a string holding every
Unicode scalar value (surrogates excluded): whatever survives did not match.

    .venv/Scripts/python.exe tools/gen_unicode_tables.py
"""
import os
import sys

from tokenizers import Regex, pre_tokenizers

CLASSES = [("N", r"\p{N}"), ("L", r"\p{L}"), ("M", r"\p{M}"), ("P", r"\p{P}"),
           ("S", r"\p{S}"), ("WS", r"\s")]


def ranges(cps):
    out = []
    for c in sorted(cps):
        if out and out[-1][1] + 1 == c:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out


def main():
    allcp = [c for c in range(0x110000) if not (0xD800 <= c <= 0xDFFF)]
    text = "".join(map(chr, allcp))
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_path = os.path.join(repo, "text", "unicode_tables.inc")
    lines = ["// Generated by tools/gen_unicode_tables.py from HF tokenizers' own regex engine.",
             "// Do not edit. [lo, hi] inclusive code point ranges, sorted.", ""]
    for name, pat in CLASSES:
        split = pre_tokenizers.Split(Regex(pat), behavior="removed")
        survived = set()
        for piece, (a, b) in split.pre_tokenize_str(text):
            survived.update(range(a, b))
        # offsets are char offsets into `text`, i.e. indices into allcp
        matched = [allcp[i] for i in range(len(allcp)) if i not in survived]
        rs = ranges(matched)
        print(f"{name}: {len(matched)} code points, {len(rs)} ranges", file=sys.stderr)
        lines.append(f"static const uint32_t kClass{name}[][2] = {{")
        row = []
        for lo, hi in rs:
            row.append(f"{{0x{lo:X},0x{hi:X}}}")
            if len(row) == 6:
                lines.append("    " + ",".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ",".join(row) + ",")
        lines.append("};")
        lines.append("")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(out_path, file=sys.stderr)


if __name__ == "__main__":
    main()
