#!/usr/bin/env python3
"""Expert-cache hit-rate and stall bench over `deepmoe serve` (Track R1,
docs/p4_hitrate.md).

    .venv/Scripts/python.exe tools/hitrate_bench.py --script bench/results/hitrate/long_turns.json \
        --out bench/results/hitrate/auto [--cache-gb N] [--exe build/deepmoe.exe] \
        [--shader-dir build/shaders] [--serve-arg=--gpu-prefill-min --serve-arg=256] [--env K=V]

One serve process runs a chat.py-format script (the same renderer, the same KV
continuation), with `--profile` and `DEEPMOE_ROUTE_DUMP` on. The out directory gets

    events.jsonl    every protocol event, with the host's receive time
    profile.jsonl   the engine's design 13.1 record, one line per decode step
    route.bin       the engine's routing dump (runtime/engine.h), one record per step
    turns.json      chat.py's per-turn stats plus the step layout of each request
    transcript.md   the conversation

`tools/hitrate_sim.py OUT` turns them into the per-128-step curve and replays the
same routing through tools/cache_sim.py's LRU.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

sys.dont_write_bytecode = True
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "tools"))
import chat  # noqa: E402


class BenchServer(chat.Server):
    """chat.Server with a free-form command line, extra environment and an event log."""

    def __init__(self, args, out_dir):
        cmd = [args.exe, "serve", "--model", chat.MODEL, "--max-context", str(args.max_context),
               "--engram-tables", os.path.join(REPO, "tests", "data", "l3"),
               "--profile", os.path.join(out_dir, "profile.jsonl")]
        if args.cache_gb:
            cmd += ["--cache-gb", str(args.cache_gb)]
        cmd += args.serve_arg
        env = dict(os.environ)
        env["DEEPMOE_ROUTE_DUMP"] = os.path.join(out_dir, "route.bin")
        if args.shader_dir:
            env["DEEPMOE_SHADER_DIR"] = args.shader_dir
        for kv in args.env:
            k, v = kv.split("=", 1)
            env[k] = v
        for f in ("profile.jsonl", "route.bin", "events.jsonl"):
            p = os.path.join(out_dir, f)
            if os.path.exists(p):
                os.remove(p)
        self.events = open(os.path.join(out_dir, "events.jsonl"), "w", encoding="utf-8", newline="\n")
        self.t0 = time.time()
        self.log = open(os.path.join(out_dir, "serve.log"), "wb")
        self.p = subprocess.Popen(cmd, cwd=REPO, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                  stderr=self.log, bufsize=0, env=env)
        self.cmd = cmd
        self.ready = self.read_event()
        if self.ready.get("event") != "ready":
            raise SystemExit(f"server did not start: {self.ready}")

    def read_event(self):
        ev = super().read_event()
        rec = dict(ev)
        rec["host_s"] = round(time.time() - self.t0, 4)
        self.events.write(json.dumps(rec, ensure_ascii=False) + "\n")
        self.events.flush()
        return ev


def write_heat_from_route(route_path: str, out_path: str) -> int:
    """Turn a run's route.bin into a DEEPMOE_HEAT_FILE for the next round."""
    sys.path.insert(0, os.path.join(REPO, "tools"))
    import hitrate_sim  # noqa: E402
    import numpy as np  # noqa: E402
    _step, _pos, ids, _hits = hitrate_sim.load_route(route_path)
    counts = np.bincount(ids.astype(np.int64).ravel(), minlength=40 * 384)
    order = np.argsort(-counts, kind="stable")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"// generated by tools/hitrate_bench.py from {route_path}\n")
        for k in order:
            f.write(f"{{{k // 384}, {k % 384}, {int(counts[k])}}},\n")
    return int(len(order))


def round_stats(events_path: str) -> dict:
    """Aggregate the `done` events of one round."""
    gen = steps = prefill_tokens = 0
    decode_ms = prefill_ms = hit_weighted = 0.0
    turns = 0
    with open(events_path, encoding="utf-8") as f:
        for line in f:
            try:
                ev = json.loads(line)
            except json.JSONDecodeError:
                continue
            if ev.get("event") != "done":
                continue
            turns += 1
            gen += int(ev.get("generated", 0))
            steps += int(ev.get("decode_steps", 0))
            prefill_tokens += int(ev.get("prefill_tokens", 0))
            decode_ms += float(ev.get("decode_ms", 0.0))
            prefill_ms += float(ev.get("prefill_ms", 0.0))
            hit_weighted += float(ev.get("decode_hit_rate", 0.0)) * int(ev.get("decode_steps", 0))
    return {
        "turns": turns,
        "generated": gen,
        "decode_steps": steps,
        "prefill_tokens": prefill_tokens,
        "decode_ms": decode_ms,
        "prefill_ms": prefill_ms,
        "decode_hit_rate": (hit_weighted / steps) if steps else 0.0,
        "decode_tok_s": (steps * 1e3 / decode_ms) if decode_ms > 0 else 0.0,
    }


def auto_tune(args, script: dict, cargs, enc) -> int:
    """N fresh-server rounds; each round feeds the previous round's route heat."""
    curve = []
    heat = args.heat_file
    for r in range(args.auto_tune):
        out_r = os.path.join(args.out, f"round_{r}")
        os.makedirs(out_r, exist_ok=True)
        ra = argparse.Namespace(**vars(args))
        ra.out = out_r
        ra.env = list(args.env)
        if not any(k.startswith("DEEPMOE_BACKFILL=") for k in ra.env):
            ra.env.append("DEEPMOE_BACKFILL=1")
        if heat:
            ra.env.append("DEEPMOE_HEAT_FILE=" + heat)
        server = BenchServer(ra, out_r)
        c = chat.Chat(server, enc, cargs)
        try:
            chat.run_script(c, server, script, os.path.join(out_r, "transcript.md"),
                            os.path.join(out_r, "turns.json"))
        finally:
            server.close()
            server.events.close()
        st = round_stats(os.path.join(out_r, "events.jsonl"))
        heat_out = os.path.join(args.out, f"heat_round_{r}.inc")
        try:
            write_heat_from_route(os.path.join(out_r, "route.bin"), heat_out)
            heat_next = heat_out
        except Exception as exc:  # a round that crashed still leaves stats
            print(f"round {r}: heat write failed: {exc}", flush=True)
            heat_next = ""
        row = dict(round=r, heat_in=heat, heat_out=heat_next, **st)
        curve.append(row)
        print(f"round {r}: turns={st['turns']} hit={st['decode_hit_rate']:.4f} "
              f"tok_s={st['decode_tok_s']:.2f} prefill_tok={st['prefill_tokens']}", flush=True)
        heat = heat_next or heat
    with open(os.path.join(args.out, "auto_tune.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(curve, f, ensure_ascii=False, indent=1)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", default="")
    ap.add_argument("--requests", default="",
                    help='raw {"requests":[{"prompt_ids":[..],"max_tokens":N,..}]} instead of a chat script')
    ap.add_argument("--idle-s", type=float, default=0.0,
                    help="seconds to wait after ready before the first request (the P3 backfill's idle time)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--exe", default=os.path.join(REPO, "build", "deepmoe.exe"))
    ap.add_argument("--shader-dir", default="")
    ap.add_argument("--cache-gb", type=int, default=0)
    ap.add_argument("--max-context", type=int, default=4096)
    ap.add_argument("--serve-arg", action="append", default=[])
    ap.add_argument("--env", action="append", default=[])
    ap.add_argument("--repeat", type=int, default=1, help="run the script this many times back to back")
    ap.add_argument("--auto-tune", type=int, default=0,
                    help="run N fresh-server rounds; each round generates a heat file from its route dump")
    ap.add_argument("--heat-file", default="", help="initial DEEPMOE_HEAT_FILE for auto-tune round 0")
    ap.add_argument("--write-heat", default="", help="write this run's route heat to a DEEPMOE_HEAT_FILE")
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    os.makedirs(args.out, exist_ok=True)
    enc = chat.load_encoding()
    server = BenchServer(args, args.out)
    print(f"ready: {json.dumps(server.ready)}", flush=True)
    if args.idle_s:
        time.sleep(args.idle_s)
    if args.requests:
        with open(args.requests, encoding="utf-8") as f:
            reqs = json.load(f)["requests"]
        stats = []
        try:
            for r in reqs:
                server.send(dict({"op": "generate", "stop_ids": [1]}, **r))
                while True:
                    ev = server.read_event()
                    if ev.get("event") == "done":
                        stats.append(ev)
                        print(json.dumps({k: ev[k] for k in ("prompt_tokens", "prefill_mode", "prefill_ms",
                                                            "decode_steps", "tok_s", "decode_hit_rate")}),
                              flush=True)
                        break
                    if ev.get("event") == "error":
                        raise SystemExit(ev["message"])
        finally:
            server.close()
            server.events.close()
        with open(os.path.join(args.out, "turns.json"), "w", encoding="utf-8", newline="\n") as f:
            json.dump({"server": server.ready, "turns": stats, "cmd": server.cmd, "env": args.env}, f, indent=1)
        return 0
    cargs = argparse.Namespace(think=False, temp=1.0, top_p=0.95, max_tokens=256, seed=None, system="")
    with open(args.script, encoding="utf-8") as f:
        script = json.load(f)
    if args.auto_tune > 0:
        server.close()
        server.events.close()
        return auto_tune(args, script, cargs, enc)
    c = chat.Chat(server, enc, cargs)
    if args.repeat > 1:
        turns = []
        for r in range(args.repeat):
            for t in script["turns"]:
                t2 = dict(t)
                if r and t is script["turns"][0]:
                    t2["reset"] = True
                turns.append(t2)
        script = dict(script, turns=turns)
    try:
        chat.run_script(c, server, script, os.path.join(args.out, "transcript.md"),
                        os.path.join(args.out, "turns.json"))
    finally:
        server.close()
        server.events.close()
    with open(os.path.join(args.out, "turns.json"), encoding="utf-8") as f:
        doc = json.load(f)
    doc["cmd"] = server.cmd
    doc["env"] = args.env
    with open(os.path.join(args.out, "turns.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
    if args.write_heat:
        print(f"wrote {write_heat_from_route(os.path.join(args.out, 'route.bin'), args.write_heat)} heat rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
