"""Render bench/results/perf_ledger.jsonl into docs/STATUS.md's measured table.

The ledger is appended to only by `tools/perf_report.py --record LABEL`, which
copies each number from the run's own files and the run's provenance.json (what
commit, which files dirty, which binary and shaders, which DEEPMOE_* switches).
This script rewrites the block between

    <!-- perf-ledger:begin -->
    <!-- perf-ledger:end -->

in docs/STATUS.md from it, so the table there is never typed by hand. Prose
around it interprets the rows; it does not restate them.

    python tools/perf_ledger.py            # print the table
    python tools/perf_ledger.py --write    # replace the block in docs/STATUS.md
    python tools/perf_ledger.py --check    # exit 1 if the block is stale (for a gate)
    python tools/perf_ledger.py --refresh  # recompute every chat row from its run directory
                                           # (after perf_report gains a metric; provenance kept)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "bench" / "results" / "perf_ledger.jsonl"
STATUS = ROOT / "docs" / "STATUS.md"
BEGIN, END = "<!-- perf-ledger:begin -->", "<!-- perf-ledger:end -->"


def load(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def code(p: dict) -> str:
    c = p.get("commit") or "?"
    if p.get("dirty"):
        c += f"+{len(p['dirty'])} dirty ({p.get('diff_sha') or '?'})"
    if p.get("after_the_fact"):
        c += " †"
    return f"`{c}`"


def switches(p: dict) -> str:
    env = {k: v for k, v in p.get("env", {}).items()
           if k not in ("DEEPMOE_ROUTE_DUMP", "DEEPMOE_MODEL_DIR", "DEEPMOE_SHADER_DIR",
                        "DEEPMOE_LONGCTX_DIR")}
    s = " ".join(f"{k.removeprefix('DEEPMOE_')}={v}" for k, v in env.items())
    return s or "–"


def start_kv(c: dict) -> str:
    # Tokens serve restored from its disk prefix cache before turn 1 -- the
    # previous run's last context, replayed into the expert cache. 0 is a clean
    # start; rows before STATUS 0s mostly are not.
    n = c.get("kv_restored")
    return "?" if n is None else ("0" if n == 0 else f"**{n}**")


def fmt(v, nd: int = 2) -> str:
    return "–" if v is None else f"{v:.{nd}f}"


def foreign_writes(p: dict) -> str:
    d = p.get("disks_during_run")
    if not d:
        return "?"
    w = sum(v["write_MB"] for k, v in d.items() if isinstance(v, dict))
    return f"**{w:,.0f} MB ⚠**" if w > 500 else f"{w:,.0f} MB"


def bg(p: dict) -> str:
    i = p.get("idle") or {}
    return "?" if i.get("gpu_busy_mean") is None else f"{i['gpu_busy_mean']:g}%"


def render(rows: list[dict]) -> str:
    out = [BEGIN,
           "<!-- generated by tools/perf_ledger.py from bench/results/perf_ledger.jsonl; "
           "do not edit by hand -->", ""]
    chat = [r for r in rows if "chat" in r]
    if chat:
        out += ["**对话（`tools/hitrate_bench.py` → `perf_report --chat --record`，每 token ms）**", "",
                "| # | label | code | switches | start KV | bg GPU | disk writes | decode tok/s | ms/tok | compute (attn/moe/tail/engram) "
                "| NVMe stall (floor) | ms/miss | other | hit | prefill s |",
                "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for i, r in enumerate(rows):
            if "chat" not in r:
                continue
            c, p = r["chat"], r.get("provenance", {})
            comp = c["attn"] + c["moe_gpu"] + c["tail"] + c["engram"]
            out.append(
                f"| {i} | {r['label']} | {code(p)} | {switches(p)} | {start_kv(c)} | {bg(p)} | {foreign_writes(p)} | **{c['tok_s']:.3f}** | "
                f"{c['per_tok']:.1f} | {comp:.1f} ({c['attn']:.1f}/{c['moe_gpu']:.1f}/"
                f"{c['tail']:.1f}/{c['engram']:.1f}) | {c['stall']:.1f} ({c['io_floor']:.1f} @ "
                f"{r['disk_gbs']} GB/s) | {fmt(c.get('stall_per_miss'))} | {c['other']:.1f} | {c['hit']:.4f} | "
                f"{fmt(c.get('prefill_s'), 1)} |")
        out.append("")
    hot = [r for r in rows if "hot" in r]
    if hot:
        out += ["**热步（`perf_report --capture --record`，全部 expert 驻留，每 token ms）**", "",
                "| # | label | code | switches | bg GPU | GPU span (pass range) | weight floor | barriers | top excess |",
                "|---|---|---|---|---|---|---|---|---|"]
        for i, r in enumerate(rows):
            if "hot" not in r:
                continue
            h, p = r["hot"], r.get("provenance", {})
            top = ", ".join(f"{s['stage']} {s['excess']:.2f}" for s in h["stages"][:4])
            rng = h.get("span_range")
            rng = f" ({rng[0]:.1f}–{rng[1]:.1f})" if rng else " (1 pass)"
            out.append(f"| {i} | {r['label']} | {code(p)} | {switches(p)} | {bg(p)} | **{h['span']:.2f}**{rng} | "
                       f"{h['floor']:.2f} | {h['barriers']:.2f} | {top} |")
        out.append("")
    out += ["`†` = 这次运行早于 `provenance.json`，code 列是**记录时**的树与二进制，不是运行时的。"
            "ms/miss 是 decode 步（hit > 0.8）的 NVMe stall 对该步 miss 数的回归斜率：同配置复跑只动 ~1%，比 tok/s 稳得多，IO 改动看它。"
            "start KV 是 serve 启动时从盘上 KV 缓存恢复并重放进 expert cache 的 token 数（上一次运行的最后一段上下文；0 = 干净起步，STATUS §7 0s 之前的行大多不是）。"
            "disk writes 是运行期间所有 NVMe 的写入量（引擎自己只写几 MB 日志；>500 MB 标 ⚠：有别的程序在写同一块盘，IO 数字不可信）。"
            "bg GPU 是开跑前 1 s 的 `gpu_busy_percent` 均值（别的进程占着同一块 LPDDR5X，会让每个 kernel 慢几个百分点）。"
            "`dirty` 后面是 `git diff HEAD` 的哈希；完整出处（exe / shader 哈希、全部开关、DPM 状态）在 ledger 那一行里。",
            END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", type=Path, default=LEDGER)
    ap.add_argument("--status", type=Path, default=STATUS)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--refresh", action="store_true")
    a = ap.parse_args()
    if a.refresh:
        sys.path.insert(0, str(ROOT / "tools"))
        import perf_report
        rows = load(a.ledger)
        for r in rows:
            if "chat" in r:
                c = perf_report.chat_budget(ROOT / r["chat_dir"], r["disk_gbs"])
                r["chat"] = {k: (round(v, 4) if isinstance(v, float) else v) for k, v in c.items()}
        a.ledger.write_text("".join(json.dumps(r, separators=(",", ":")) + "\n" for r in rows),
                            encoding="utf-8")
        return 0
    table = render(load(a.ledger))
    if not (a.write or a.check):
        print(table)
        return 0
    doc = a.status.read_text(encoding="utf-8")
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < i:
        print(f"{a.status}: no {BEGIN} ... {END} block", file=sys.stderr)
        return 2
    new = doc[:i] + table + doc[j + len(END):]
    if a.check:
        if new != doc:
            print(f"{a.status}: the perf-ledger block is stale; run tools/perf_ledger.py --write",
                  file=sys.stderr)
            return 1
        return 0
    a.status.write_text(new, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
