"""Render bench/results/perf_ledger.jsonl into docs/STATUS.md's measured table.

The ledger is appended to only by `tools/perf_report.py --record LABEL`, which
copies each number from the run's own files and the run's provenance.json (what
commit, which files dirty, which binary and shaders, which DEEPMOE_* switches).
This script rewrites the block between

    <!-- perf-ledger:begin -->
    <!-- perf-ledger:end -->

in docs/STATUS.md from it, so the table there is never typed by hand. Prose
around it interprets the rows; it does not restate them.

    python tools/perf_ledger.py            # print the table
    python tools/perf_ledger.py --write    # replace the block in docs/STATUS.md
    python tools/perf_ledger.py --check    # exit 1 if the block is stale (for a gate)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "bench" / "results" / "perf_ledger.jsonl"
STATUS = ROOT / "docs" / "STATUS.md"
BEGIN, END = "<!-- perf-ledger:begin -->", "<!-- perf-ledger:end -->"


def load(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]


def code(p: dict) -> str:
    c = p.get("commit") or "?"
    if p.get("dirty"):
        c += f"+{len(p['dirty'])} dirty ({p.get('diff_sha') or '?'})"
    if p.get("after_the_fact"):
        c += " †"
    return f"`{c}`"


def switches(p: dict) -> str:
    env = {k: v for k, v in p.get("env", {}).items()
           if k not in ("DEEPMOE_ROUTE_DUMP", "DEEPMOE_MODEL_DIR", "DEEPMOE_SHADER_DIR",
                        "DEEPMOE_LONGCTX_DIR")}
    s = " ".join(f"{k.removeprefix('DEEPMOE_')}={v}" for k, v in env.items())
    return s or "–"


def render(rows: list[dict]) -> str:
    out = [BEGIN,
           "<!-- generated by tools/perf_ledger.py from bench/results/perf_ledger.jsonl; "
           "do not edit by hand -->", ""]
    chat = [r for r in rows if "chat" in r]
    if chat:
        out += ["**对话（`tools/hitrate_bench.py` → `perf_report --chat --record`，每 token ms）**", "",
                "| # | label | code | switches | decode tok/s | ms/tok | compute (attn/moe/tail/engram) "
                "| NVMe stall (floor) | other | hit |",
                "|---|---|---|---|---|---|---|---|---|---|"]
        for i, r in enumerate(rows):
            if "chat" not in r:
                continue
            c, p = r["chat"], r.get("provenance", {})
            comp = c["attn"] + c["moe_gpu"] + c["tail"] + c["engram"]
            out.append(
                f"| {i} | {r['label']} | {code(p)} | {switches(p)} | **{c['tok_s']:.3f}** | "
                f"{c['per_tok']:.1f} | {comp:.1f} ({c['attn']:.1f}/{c['moe_gpu']:.1f}/"
                f"{c['tail']:.1f}/{c['engram']:.1f}) | {c['stall']:.1f} ({c['io_floor']:.1f} @ "
                f"{r['disk_gbs']} GB/s) | {c['other']:.1f} | {c['hit']:.4f} |")
        out.append("")
    hot = [r for r in rows if "hot" in r]
    if hot:
        out += ["**热步（`perf_report --capture --record`，全部 expert 驻留，每 token ms）**", "",
                "| # | label | code | switches | GPU span | weight floor | barriers | top excess |",
                "|---|---|---|---|---|---|---|---|"]
        for i, r in enumerate(rows):
            if "hot" not in r:
                continue
            h, p = r["hot"], r.get("provenance", {})
            top = ", ".join(f"{s['stage']} {s['excess']:.2f}" for s in h["stages"][:4])
            out.append(f"| {i} | {r['label']} | {code(p)} | {switches(p)} | **{h['span']:.2f}** | "
                       f"{h['floor']:.2f} | {h['barriers']:.2f} | {top} |")
        out.append("")
    out += ["`†` = 这次运行早于 `provenance.json`，code 列是**记录时**的树与二进制，不是运行时的。"
            "`dirty` 后面是 `git diff HEAD` 的哈希；完整出处（exe / shader 哈希、全部开关、DPM 状态）在 ledger 那一行里。",
            END]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", type=Path, default=LEDGER)
    ap.add_argument("--status", type=Path, default=STATUS)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    table = render(load(a.ledger))
    if not (a.write or a.check):
        print(table)
        return 0
    doc = a.status.read_text(encoding="utf-8")
    i, j = doc.find(BEGIN), doc.find(END)
    if i < 0 or j < i:
        print(f"{a.status}: no {BEGIN} ... {END} block", file=sys.stderr)
        return 2
    new = doc[:i] + table + doc[j + len(END):]
    if a.check:
        if new != doc:
            print(f"{a.status}: the perf-ledger block is stale; run tools/perf_ledger.py --write",
                  file=sys.stderr)
            return 1
        return 0
    a.status.write_text(new, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
